### ISSUE TITLE
Installation LD problem

### ISSUE THREAD

**Issue by demonoff** [radareorg/radare2#18804]
## Environment
On Ubuntu 18.04 after cloning and `radare2/sys/install.sh` I get the following error

```
[r2r 336] CC load.c
[r2r 337] CC run.c
[r2r 338] CC r2r.c
run.c: In function 'handle_sigchld':
run.c:394:2: warning: ignoring return value of 'write', declared with attribute warn_unused_result [-Wunused-result]
  write (sigchld_pipe[1], &b, 1);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
run.c: In function 'sigchld_th':
run.c:440:4: warning: ignoring return value of 'write', declared with attribute warn_unused_result [-Wunused-result]
    write (proc->killpipe[1], &r, 1);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
run.c: In function 'r2r_subprocess_fini':
run.c:477:2: warning: ignoring return value of 'write', declared with attribute warn_unused_result [-Wunused-result]
  write (sigchld_pipe[1], &b, 1);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
run.c: In function 'r2r_subprocess_stdin_write':
run.c:716:2: warning: ignoring return value of 'write', declared with attribute warn_unused_result [-Wunused-result]
  write (proc->stdin_fd, buf, buf_size);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
LD r2r
/home/user1/anaconda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: /home/user1/cc/arch/old_dat_002/tmp/_2021/_00_003_hack/radare2/libr/util/libr_util.so: undefined reference to `clock_gettime'
collect2: error: ld returned 1 exit status
../rules.mk:98: recipe for target 'r2r' failed
make[2]: *** [r2r] Error 1
Makefile:14: recipe for target 'all' failed
make[1]: *** [all] Error 1
Makefile:50: recipe for target 'all' failed
make: *** [all] Error 2
```
Appreciate any sugestions....

**Comment by trufae** [comment]
I can confirm that r2 builds fine on ubuntu18.04, i have tested this on the CI and everything runs as expected. There must be something older in your system around.. but still this is a bug in the r2 codebase. So i have improved the checking in this PR and will merge when the CI finishes https://github.com/radareorg/radare2/pull/18805/checks?check_run_id=2752238138

**Comment by trufae** [comment]
Should be fixed now. can you confirm? ill reopen if not

**Comment by demonoff** [comment]
cloned again and this time the installation went well :) thank you for your help!
