### ISSUE TITLE
radare2 build fails for kernels without transparent huge page (THP) support

### ISSUE THREAD

**Issue by fritzr** [radareorg/radare2#15304]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits                             | Centos release 6.9 (Final) Linux 2.6.32-696.23.1.el6.centos.plus.x86_64
| r2 -v full output, **not truncated**     | radare2 4.0.0-git 23070 @ linux-x86-64 git.3.9.0-223-gd9fa40956 commit: d9fa409563736e300d2d29ee7a97b0aef272a882 build: 2019-10-17__13:52:00

### Expected behavior

I expect the following to succeed out-of-the-box:

```sh
./configure --prefix=$HOME/.local && make && make install
```

### Actual behavior

```sh
$ ./configure --prefix=$HOME
# [...] OK
$ make
# [...]
DIR debug
make[3]: Entering directory `$RADARE_SRC/libr/debug'
make[4]: Entering directory `$RADARE_SRC/libr/debug'
gcc -c  -MD   -fPIC -g -Wall -D__UNIX__=1 -DR2_PLUGIN_INCORE -Ip/libbfwbf/include -I$RADARE_SRC/libr/../shlr/bochs/include/ -I$RADARE_SRC/libr/../shlr/gdb/include/ -I$RADARE_SRC/libr/../shlr/qnx/include/ -Ip/librapwrap/include -I$RADARE_SRC/libr/../shlr/windbg/ -DXNU_USE_PTRACE=0 -I../bin/format/elf -I$RADARE_SRC/libr -I$RADARE_SRC/libr/include -fvisibility=hidden -o p/debug_native.o p/debug_native.c
p/debug_native.c: In function ‘linux_map_thp’:
p/debug_native.c:1148:20: error: ‘MADV_HUGEPAGE’ undeclared (first use in this function)
 1148 |   num, addr, size, MADV_HUGEPAGE);
      |                    ^~~~~~~~~~~~~
p/debug_native.c:1148:20: note: each undeclared identifier is reported only once for each function it appears in
make[4]: *** [p/debug_native.o] Error 1
make[4]: Leaving directory `$RADARE_SRC/libr/debug'
make[3]: *** [foo] Error 2
make[3]: Leaving directory `$RADARE_SRC/libr/debug'
make[2]: *** [debug] Error 2
make[2]: Leaving directory `$RADARE_SRC/libr'
make[1]: *** [all] Error 2
make[1]: Leaving directory `$RADARE_SRC/libr'
make: *** [all] Error 2
```

### Steps to reproduce the behavior 

The `madvise(2)` system call does not always support `MADV_HUGEPAGE` on Linux. Specifically, support for transparent huge pages (THP) and the `MADV_HUGEPAGE` macro is only introduced as early as Linux 2.6.38, and even then only if the kernel was configured with `CONFIG_TRANSPARENT_HUGEPAGE`. On such systems the macro is unavailable.

### Additional Logs, screenshots, source-code,  configuration dump, ...

This was broken by PR #14730. I will submit a PR shortly which no-ops the `linux_map_thp` function from [debug_native.c:1116](/radareorg/radare2/tree/master/libr/debug/p/debug_native.c#L1116) if `MADV_HUGEPAGE` is not defined. It might be more portable to check the availability of THP as part of `configure` or check the kernel version from `<linux/version.h>`, but I believe a simple `#if defined(MADV_HUGEPAGE)` guard is sufficient in practice.
