### ISSUE TITLE
Build fails with Capstone 5

### ISSUE THREAD

**Issue by hamarituc** [radareorg/radare2#21204]
## Environment

```sh
# copypaste this script into your shell and replace it with the output
date
r2 -v
uname -ms
```

Not applicable, as Radare2 fails to compile

## Description

The build of version 5.8.0 fails if using capston 5 from the system libraries.

```
/var/tmp/portage/dev-util/radare2-5.8.0/work/radare2-5.8.0/libr/..//libr/anal/p/anal_arm_cs.c: In function ‘analop64_esil’:
/var/tmp/portage/dev-util/radare2-5.8.0/work/radare2-5.8.0/libr/..//libr/anal/p/anal_arm_cs.c:1324:14: error: ‘ARM64_INS_ADDG’ undeclared (first use in this function); did you mean ‘ARM64_INS_ADDV’?
 1324 |         case ARM64_INS_ADDG:
      |              ^~~~~~~~~~~~~~
      |              ARM64_INS_ADDV
/var/tmp/portage/dev-util/radare2-5.8.0/work/radare2-5.8.0/libr/..//libr/anal/p/anal_arm_cs.c:1324:14: note: each undeclared identifier is reported only once for each function it appears in
/var/tmp/portage/dev-util/radare2-5.8.0/work/radare2-5.8.0/libr/..//libr/anal/p/anal_arm_cs.c: In function ‘anop64’:
/var/tmp/portage/dev-util/radare2-5.8.0/work/radare2-5.8.0/libr/..//libr/anal/p/anal_arm_cs.c:3310:14: error: ‘ARM64_INS_UDF’ undeclared (first use in this function); did you mean ‘ARM64_INS_DC’?
 3310 |         case ARM64_INS_UDF:
      |              ^~~~~~~~~~~~~
      |              ARM64_INS_DC
/var/tmp/portage/dev-util/radare2-5.8.0/work/radare2-5.8.0/libr/..//libr/anal/p/anal_arm_cs.c:3398:14: error: ‘ARM64_INS_ADDG’ undeclared (first use in this function); did you mean ‘ARM64_INS_ADDV’?
 3398 |         case ARM64_INS_ADDG:
      |              ^~~~~~~~~~~~~~
      |              ARM64_INS_ADDV
/var/tmp/portage/dev-util/radare2-5.8.0/work/radare2-5.8.0/libr/..//libr/anal/p/anal_arm_cs.c:3643:14: error: ‘ARM64_INS_IRG’ undeclared (first use in this function); did you mean ‘ARM64_INS_IC’?
 3643 |         case ARM64_INS_IRG:
      |              ^~~~~~~~~~~~~
      |              ARM64_INS_IC
make[5]: *** [/var/tmp/portage/dev-util/radare2-5.8.0/work/radare2-5.8.0/libr/../global.mk:45: /var/tmp/portage/dev-util/radare2-5.8.0/work/radare2-5.8.0/libr/..//libr/anal/p/anal_arm_cs.o] Error 1
```

This error was introduced by commit 361a6ea47a6d42d9b843f97e981ac9c3fe587e9c. It doesn't fail if using the bundled version 4 of capstone, because all changes are enclosed inside `#if CS_API_MAJOR > 4`. I'm unable to find any references to `ARM64_INS_ADDG` and friends in the capstone source code. Where do they come from?

## Test

```
$ ./configure --prefix=/usr --build=x86_64-pc-linux-gnu --host=x86_64-pc-linux-gnu --mandir=/usr/share/man --infodir=/usr/share/info --datadir=/usr/share --sysconfdir=/etc --localstatedir=/var/lib --docdir=/usr/share/doc/radare2-5.8.0 --libdir=/usr/lib64 --with-syscapstone --with-syslz4 --with-sysmagic --with-sysxxhash --with-syszip
$ make
```

**Comment by trufae** [comment]
Are you sure you have the latest capstone5? Because by default r2 builds with capstone5. But as long as theres no release theres more than one capstone5..

**Comment by hamarituc** [comment]
Sorry for the noise (... and don't rely on the GitHub search even with the right branch selected :see_no_evil:). I found the needed commit in the `next`-branch. It seems we need to wait for the next release of Capstone to build packages for Radare2 5.8.0.

**Comment by trufae** [comment]
Ive been waiting more than 5 years for this release to happen.. i just keep my hope

**Comment by yaroslavyaroslav** [comment]
@hamarituc and what's that commit hash?

**Comment by hamarituc** [comment]
> @hamarituc and what's that commit hash?
> 
> It's this: `12e8258f`

As far as I can remember the first commit introducing `ARM64_INS_ADDG` is 74be6d0a51dc8486b5da1085e762b44ec5793c09.

**Comment by trufae** [comment]
R2 builds against capstone 5 by default for about 2 years. If it doesnt build you are using an old capstone5. Because theres no release for it yet. And theres no way to make conditional build per commit. Just use the one r2 picks or update your system wide capstone

**Comment by yaroslavyaroslav** [comment]
> R2 builds against capstone 5 by default for about 2 years. If it doesnt build you are using an old capstone5.

I've tried to build r2 above capstone literally on last commit in their repo — and it failed (r2, not capstone), i've tried to build it on rc2 commit and it failed as well. But the commit that I've posted recently, e.g. capstone built on it, which was taken from you build script make it succeed.
