### PR TITLE
Fix armhf/armv7 musl compatibility again

### PR DESCRIPTION
**Pull request by nmeum**
In e92d170a3b9fa70e2abacae73e30acfb3dcfc6bd, the include of `asm/ptrace.h` has been silently disabled (it is presently unclear to me why). Thereby basically reverting #13427. However, without `asm/ptrace.h` included the build will fail on musl armhf/armv7 targets with the following compilation failure:

	p/native/linux/linux_coredump.c: In function 'linux_get_arm_vfp_data':
	p/native/linux/linux_coredump.c:950:27: error: 'ARM_VFPREGS_SIZE' undeclared (first use in this function)
	  950 |  char *vfp_data = calloc (ARM_VFPREGS_SIZE + 1, 1);
	      |                           ^~~~~~~~~~~~~~~~

This commit fixes this build failure by including asm/ptrace.h again.

---

CC: @trufae

### CODE REVIEW

**Comment by trufae** [comment]
This file is not found when building for amd64, so maybe we can wrap it inside some ifdefs, but afaik including asm/ is a bad practice

**Comment by nmeum** [comment]
> This file is not found when building for amd64, so maybe we can wrap it inside some ifdefs […]

Done.

> […] but afaik including asm/ is a bad practice

Yeah, I agree I can't think of an easy alternative solution though.
